  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: env-config-app
  data:
    PASSWORD: password
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_HOST: mysql-service:3306
    SECRET_KEY: secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-mysql

data:
  init.sql: |
      SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

      CREATE DATABASE IF NOT EXISTS flask_articles;
